name: Merge Readiness

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: merge-readiness-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read
  statuses: write

jobs:
  merge-readiness:
    uses: e0da/actions/.github/workflows/callable-merge-readiness.yml@main
    secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      repository: ${{ github.repository }}
